### ISSUE TITLE
full new eeprom k4 board possible?

### ISSUE THREAD

**Issue by pakoto** [RBSC/Konami-SCC-Cartridge-Repair#1]
Could we obtain working a k4 cart using 27c0x0 eeprom and that 74hc chips merging this into new pcb? I tried to build unimapper version, but fake GALs from aliexpress makes me crazy!

**Comment by Wierzbowsky** [comment]
We have no plans to make such a cartridge. There are plenty of alternatives. For example, you can buy our cartridge from AliExpress (this is not authorized seller, but we don't care):

https://de.aliexpress.com/item/1005004754219281.html
